FROM python:3.9

WORKDIR /reportViewer

COPY config/front/public /reportViewer/public

COPY config/front/server.py /reportViewer

COPY config/requirements.txt /reportViewer




# Expose port 8080
EXPOSE 8081

RUN pip install -r requirements.txt

CMD ["python", "server.py"]
