services:
  report-viewer:
    build:
      context: .
      dockerfile: Dockerfile.report-viewer
    container_name: report-viewer
    ports:
      - "8081:8081"
    depends_on:
      - report-engine # This dependency assumes you will define 'python-app' below

  report-engine:
    build:
      context: .
      dockerfile: Dockerfile.report-engine
    container_name: report-engine
    ports:
      - "5001:5001"
    volumes:
      - ./config/back/data:/reportEngine/data 

  grafana:
    build:
      context: .
      dockerfile: Dockerfile.grafana
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  prometheus:
    build:
      context: .
      dockerfile: Dockerfile.prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
    restart: unless-stopped
    command: --config.file=/etc/prometheus/prometheus.yml

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/app.conf:/etc/nginx/conf.d/app.conf:ro
      - ./certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - report-viewer
      - grafana

  cv:
    build:
      context: .
      dockerfile: Dockerfile.cv
    container_name: cv
    ports:
      - "880:880"
    volumes:
      - ./config/node_cv/public:/usr/src/app/public
      - ./config/node_cv/pages:/usr/src/app/pages
    
volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
