# Use Node.js official image
FROM node:20

# Set working directory
WORKDIR /usr/src/app

# Copy HTML and app files
COPY config/node_cv/ .



# Install dependencies
RUN npm install

# Expose the application port
EXPOSE 880

# Start the Node.js app and keep it running
CMD ["node", "cv.js"]
