name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Set up Node
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Run unit tests
      - name: Run tests
        run: npm test

      # 5. Log in to Docker Hub
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Build & push Docker image
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: yourdockerhubuser/your-app:latest

      # 7. SSH into VPS and deploy container
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull yourdockerhubuser/your-app:latest
            docker stop my-app || true
            docker rm my-app || true
            docker run -d --name my-app -p 3000:3000 yourdockerhubuser/your-app:latest
            sleep 5
            curl -f http://localhost:3000/metrics || (echo "Health check failed" && exit 1)
